JM-6746: Generate attendance audit numbers when confirming pool attendance (jurors in waiting)
hmcts/juror-api pull request #180
Opened 2024-04-11 14:14 UTC by CCHAPMAN01

### JIRA link (if applicable) ###
https://centralgovernmentcgi.atlassian.net/browse/JM-6746

### Change description ###
- update query to fetch attendance records
  - only fetch records with an active juror_pool record
- refactor getAttendanceAuditNumber method to be reusable for jury attendance and pool attendance
- add new helper method to create pool attendance history
- update logic to generate attendance audit number when confirming pool attendance
- update unit and integration tests

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[X] No
```

2024-04-12 09:08 UTC, Ben-Edwards-cgi requested changes

2024-04-12 14:29 UTC, CCHAPMAN01 commented on src/main/java/uk/gov/hmcts/juror/api/moj/service/JurorHistoryServiceImpl.java
> +        registerHistorySystem(jurorPool, HistoryCodeMod.POOL_ATTENDANCE, otherInfo);
Good spot should be user generated ... as should the one above I created yesterday 🙈 will update both + tests 👍

2024-04-12 14:29 UTC, CCHAPMAN01 commented on src/integration-test/java/uk/gov/hmcts/juror/api/moj/controller/JurorManagementControllerITest.java
> +            "/db/JurorExpenseControllerITest_expenseRates.sql"})
Great will remove

2024-04-12 14:31 UTC, CCHAPMAN01 commented on src/main/java/uk/gov/hmcts/juror/api/moj/service/jurormanagement/JurorAppearanceServiceImpl.java
> +    @SuppressWarnings({"PMD.LawOfDemeter", "PMD.ConfusingTernary"})
Yeah the actual code wasn't confusing ... but you're right it sets a bad precedent so will invert the logic and remove the suppression

2024-04-12 14:56 UTC, CCHAPMAN01 commented on src/main/java/uk/gov/hmcts/juror/api/moj/service/jurormanagement/JurorAppearanceServiceImpl.java
> +        return prefix + String.format("%08d", attendanceAuditNumber);
added new flyway script to alter the sequence and manage the format/length in the DB as suggested 👍

2024-04-12 15:32 UTC, CCHAPMAN01 commented on src/integration-test/java/uk/gov/hmcts/juror/api/moj/controller/JurorManagementControllerITest.java
> +            "/db/JurorExpenseControllerITest_expenseRates.sql"})
test failed when removing the set up script 🙈  re-instating it fixed it, so will leave it in for now

2024-04-15 08:22 UTC, Ben-Edwards-cgi commented on src/main/java/uk/gov/hmcts/juror/api/moj/service/JurorHistoryServiceImpl.java
> +        registerHistory(jurorPool, HistoryCodeMod.JURY_ATTENDANCE, otherInfo, username);
We should have a method to pull the username from SecurityUtil so we don't need to pass it in here

2024-04-15 10:01 UTC, merged