As a developer I want to strip out the old login system (and owner from user table)
hmcts/juror-api pull request #253
Opened 2024-04-24 22:48 UTC by Ben-Edwards-cgi

### Links ###
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7139)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ajuror-api&pullRequest=%pullRequestNumber%)

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[X] No
```

2024-04-25 11:31 UTC, akikrahman1 commented
Have approved in principle as long as FE integration is done, the PR can be merged together

2024-04-25 11:33 UTC, akikrahman1 approved these changes
Need to make sure FE integration is done before merging into master

2024-05-22 10:17 UTC, npv0 requested changes

2024-05-22 10:17 UTC, npv0 commented on src/main/resources/db/migration/V1_90__temp_users.sql
do not merge

2024-05-29 15:31 UTC, merged