task/JM-6703 Unable to delete the letter from the printing queue, logs report non unique record
hmcts/juror-api pull request #469
Opened 2024-06-07 16:14 UTC by T-Sarwar

### JIRA link (if applicable) ###

https://centralgovernmentcgi.atlassian.net/browse/JM-6703

### Change description ###

Unable to delete the letter from the printing queue, logs report non unique record

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ X] No
```

2024-06-07 16:59 UTC, Ben-Edwards-cgi requested changes

2024-06-07 16:59 UTC, Ben-Edwards-cgi commented on src/main/java/uk/gov/hmcts/juror/api/moj/repository/IReissueLetterRepository.java
> +        String jurorNo, String formType, LocalDate creationDate, boolean extractedFlag);
JurorNo should be JurorNumber

2024-06-11 14:42 UTC, gregs-cgi commented on src/main/java/uk/gov/hmcts/juror/api/moj/repository/IReissueLetterRepository.java
> +        String jurorNo, String formType, LocalDate creationDate, boolean extractedFlag);
Fixed

2024-06-12 13:55 UTC, Ben-Edwards-cgi approved these changes

2024-06-12 13:55 UTC, Ben-Edwards-cgi commented on src/main/java/uk/gov/hmcts/juror/api/moj/repository/IReissueLetterRepository.java
>      List<BulkPrintData> findByJurorNoAndFormTypeAndCreationDateAndExtractedFlag(
Method name also needs updating

2024-06-13 10:12 UTC, merged